/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see legal.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[5],{353:function(ia,da,h){function ca(e,h,n){h.endsWith("/")||(h+="/");n=n||{};var r=n.disableWebsockets||!1;this.MO=n.singleServerMode||!1;h.endsWith("blackbox/")||(h+="blackbox/");this.Sl=n.uploadData||null;this.bu=n.uriData||null;this.DI=n.cacheKey||null;this.Tf=Object(f.a)(h,null,r);this.Hf=h;this.lB=e;this.df=null;this.dk=aa();this.Am=aa();this.Xv=!1;this.Qf=this.Sd=this.he=this.Qe=null;this.mf=[];this.Cw=[];this.cache={};this.timeStamp=
0;this.Ef=[];this.Ig=[];this.CB=null;this.eB=!1;this.iE=this.id=null;this.fD=this.wL=fa;this.qy=0;this.yC=!1;this.U_=1;this.Hx={};this.cx=null;this.cq(!0)}function aa(){var e={promise:null,resolve:null,reject:null,state:0,result:null,request:null,jn:function(){return 1===(e.state&1)},c_:function(){return 2===(e.state&2)},uh:function(){return!e.c_()&&!e.jn()},OZ:function(){return 4===(e.state&4)},aO:function(){e.state|=4}};e.promise=new Promise(function(f,h){e.resolve=function(){if(0===e.state||4===
e.state)e.state=1,e.result=arguments[0],f.apply(null,arguments)};e.reject=function(){if(0===e.state||4===e.state)e.state=2,h.apply(null,arguments)}});return e}function fa(){return!1}function ea(e,f,h){if(!(f in w))return!0;f=w[f];for(var n=0;n<f.length;n++){var r=e;var x=f[n];var y=h;if(x.name in r){var aa="",ba=!1;r=r[x.name];switch(x.type){case "s":aa="String";ba=Object(z.isString)(r);break;case "a":aa="Array";ba=Object(z.isArray)(r);break;case "n":aa="Number";ba=Object(z.isNumber)(r)&&Object(z.isFinite)(r);
break;case "o":aa="Object",ba=Object(z.isObject)(r)&&!Object(z.isArray)(r)}ba||y.reject('Expected response field "'+x.name+'" to have type '+aa);x=ba}else y.reject('Response missing field "'+x.name+'"'),x=!1;if(!x)return!1}return!0}h.r(da);var z=h(0);h.n(z);var x=h(1);ia=h(34);var n=h(26),f=h(370),y=h(73);h=h(297);var w={pages:[{name:"pages",type:"a"}],pdf:[{name:"url",type:"s"}],docmod:[{name:"url",type:"s"},{name:"rID",type:"s"}],health:[],tiles:[{name:"z",type:"n"},{name:"rID",type:"n"},{name:"tiles",
type:"a"},{name:"size",type:"n"}],annots:[{name:"url",type:"s"},{name:"name",type:"s"}],image:[{name:"url",type:"s"},{name:"name",type:"s"},{name:"p",type:"n"}],text:[{name:"url",type:"s"},{name:"name",type:"s"},{name:"p",type:"n"}]};ca.prototype=Object(z.extend)(ca.prototype,{cV:function(){var e=this;return new Promise(function(f,h){var n=new XMLHttpRequest;n.open("GET",e.Hf+"ck");n.withCredentials=e.Xm();n.onreadystatechange=function(){n.readyState===XMLHttpRequest.DONE&&(200===n.status?f():h())};
n.send()})},u2:function(e,f){this.wL=e||fa;this.fD=f||fa},TI:function(){var e=this;this.Am=aa();this.dk=aa();return this.Tf.vB().then(function(){e.Xv=!1;e.id=null;e.eB=!1;return e.cV()})},WD:function(){this.wL();this.px();this.Qe&&(this.Qe.uh()?this.ef(this.Qe.request):this.Qe.jn()&&this.fD(this.Qe.result.url,"pdf")&&(this.Qe=null,this.wN()));this.Qf&&this.Qf.uh()&&this.ef(this.Qf.request);this.he&&this.he.uh()?this.ef(this.he.request):this.Sd&&this.Sd.uh()&&this.kL(this.Sd.request);var e;for(e=0;e<
this.Ef.length;e++)this.Ef[e]&&this.Ef[e]&&(this.Ef[e].uh()?this.ef(this.Ef[e].request):this.Ef[e].jn()&&this.fD(this.Ef[e].result.url,"image")&&(this.Ef[e]=null,this.ny(e)));for(e=0;e<this.Ig.length;e++)this.Ig[e]&&this.Ig[e]&&this.Ig[e].uh()&&!this.Ig[e].OZ()&&this.ef(this.Ig[e].request);for(e=0;e<this.mf.length;e++)this.mf[e]&&this.mf[e].uh()&&this.ef(this.mf[e].request)},px:function(){var e=this;this.Xv||(this.timeStamp=Date.now(),this.Tf.OE(function(f){e.f0(f)}).then(function(){clearInterval(e.KD);
e.KD=null},function(f){Object(x.e)("Blackbox connection failed:"+f);e.Xv=!1;if(!e.KD){var h=0;e.eB=!0;e.iE=0;e.KD=setInterval(function(){50>h++&&e.WD()},5E3)}}),this.Xv=!0)},E4:function(){var e=this,f=createPromiseCapability();if(this.Sl){var h=new FormData;h.append("file",this.Sl.fileHandle,this.Sl.fileHandle.name);var w=this.Sl.loadCallback;var x="upload";var y=this.Sl.extension}else if(this.bu){h={uri:this.bu.uri,D7:this.bu.shareId};h=Object.keys(h).map(function(e){return e+"="+(h[e]?encodeURIComponent(h[e]):
"")}).join("&");var z="application/x-www-form-urlencoded; charset=UTF-8";w=this.bu.loadCallback;x="url";y=this.bu.extension}else return Promise.resolve();var aa=new XMLHttpRequest;aa.open("POST",Object(n.i)(e.Hf,"AuxUpload?ext="+y+"&type="+x+"&bcid="+this.Tf.clientId));aa.withCredentials=this.Xm();z&&aa.setRequestHeader("Content-Type",z);aa.addEventListener("load",function(){if(aa.readyState===aa.DONE&&200===aa.status){var h=JSON.parse(aa.response);e.lB=h.uri;w(h);f.resolve(h)}});aa.addEventListener("error",
function(){f.reject(aa.statusText+" "+JSON.stringify(aa))});this.Sl&&null!=this.Sl.onProgress&&(aa.upload.onprogress=function(f){e.Sl.onProgress(f)});aa.send(h);return f.promise},M2:function(e){this.cx=e},QY:function(e){this.password&&this.dk.jn()?e(this.password):this.cx(e)},i1:function(e){this.password=e||null;this.dk.jn()||(this.px(),this.ef({t:"pages"}));return this.dk.promise},Ct:function(e){this.CB=e||null;this.dk.jn()||(this.px(),this.ef({t:"pages"}));return this.dk.promise},VI:function(e){e=
Object.assign(e,{uri:encodeURIComponent(this.lB)});this.CB&&(e.ext=this.CB);this.df&&(e.c=this.df);this.password&&(e.pswd=this.password);this.DI&&(e.cacheKey=this.DI);return e},ef:function(e){e=this.VI(e);this.Tf.send(e)},Bj:function(e){return e},f0:function(e){var f=this,h=e.data,n=e.err,w=e.t;if(n&&f.cx&&"This document could not be decrypted with the given password"===n)f.cx(function(e){f.i1(e)});else switch(w){case "upload":n?f.F4.reject(n):f.F4.resolve("Success");break;case "pages":n?f.dk.reject(n):
ea(h,w,f.dk)&&f.dk.resolve(h);break;case "config":n?f.Am.reject(n):ea(h,w,f.Am)&&(h.id&&(f.id=h.id),h.serverVersion&&(f.T4=h.serverVersion,Object(x.f)("[WebViewer Server] server version: "+f.T4)),h.serverID?(f.qy=h.serverID===f.iE&&f.yC?f.qy+1:0,f.iE=h.serverID):f.qy=0,f.yC=!1,f.Am.resolve(h));break;case "health":n?f.Am.reject(n):ea(h,w,f.Am)&&(h=h.unhealthy,f.MO&&h?Object(x.h)("Server failed health check. Single server mode ignoring check."):!f.j6&&h&&1>=f.qy&&(f.yC=!0,f.TI().then(function(){f.WD()},
function(){f.WD()})));break;case "pdf":h.url=f.Hf+"../"+encodeURI(h.url)+"?bcid="+this.Tf.clientId;n?f.Qe.reject(n):ea(h,w,f.Qe)&&f.Qe.resolve(h);break;case "docmod":h.url=f.Hf+"../"+encodeURI(h.url)+"?bcid="+this.Tf.clientId;n?f.Hx[h.rID].reject(n):ea(h,w,f.Qe)&&f.Hx[h.rID].resolve(h);break;case "xod":if(n)this.he&&this.he.uh()&&this.he.reject(n),this.Sd&&this.Sd.uh()&&this.Sd.reject(n);else if(h.notFound)h.noCreate||this.he&&this.he.uh()&&this.he.resolve(h),this.Sd&&this.Sd.uh()&&this.Sd.resolve(h);
else{h.url&&(h.url=f.Hf+"../"+encodeURI(h.url)+"?bcid="+this.Tf.clientId);if(!this.Sd||this.Sd.jn())this.Sd=aa(),this.Sd.request={t:"xod",noCreate:!0};this.he||(this.he=aa(),this.he.request={t:"xod"});this.Sd.resolve(h);this.he.resolve(h)}break;case "annots":if(n)f.Qf.reject(n);else if(ea(h,w,f.Qf)){f.Qf.aO();var z=new XMLHttpRequest;e=f.Hf+"../"+encodeURI(h.url);var ca=h.hasAppearance?e+".xodapp?bcid="+this.Tf.clientId:null;e+="?bcid="+this.Tf.clientId;z.open("GET",e);z.responseType="text";z.withCredentials=
this.Xm();z.addEventListener("load",function(){z.readyState===z.DONE&&200===z.status&&f.Qf.resolve({gF:z.response,qI:ca})});z.addEventListener("error",function(){f.Qf.reject(z.statusText+" "+JSON.stringify(z))});z.send()}break;case "image":var da=this.Ef[h.p];n?da.promise.reject(n):ea(h,w,da)&&(da.result=h,da.result.url=f.Hf+"../"+encodeURI(da.result.url)+"?bcid="+this.Tf.clientId,da.resolve(da.result));break;case "tiles":da=h.rID;e=this.mf[da];this.mf[da]=null;this.Cw.push(da);if(n)e.reject(n);else if(ea(h,
w,e)){for(n=0;n<h.tiles.length;n++)h.tiles[n]=f.Hf+"../"+encodeURI(h.tiles[n])+"?bcid="+this.Tf.clientId;e.resolve(h)}break;case "text":da=this.Ig[h.p];if(n)da.reject(n);else if(ea(h,w,da)){da.aO();var fa=new XMLHttpRequest;fa.open("GET",f.Hf+"../"+encodeURI(h.url)+"?bcid="+this.Tf.clientId);fa.withCredentials=this.Xm();fa.addEventListener("load",function(){fa.readyState===fa.DONE&&200===fa.status&&(da.result=JSON.parse(fa.response),da.resolve(da.result))});fa.addEventListener("error",function(e){da.reject(fa.statusText+
" "+JSON.stringify(e))});fa.send()}break;case "progress":"loading"===h.t&&f.trigger(y.a.Events.DOCUMENT_LOADING_PROGRESS,[h.bytes,h.total])}},nK:function(){this.px();return this.Am.promise},dX:function(){this.Qf||(this.Qf=aa(),this.Qf.request={t:"annots"},this.ef(this.Qf.request));return this.Qf.promise},ny:function(e){this.Ef[e]||(this.Ef[e]=aa(),this.Ef[e].request={t:"image",p:e},this.ef(this.Ef[e].request));return this.Ef[e].promise},j1:function(e){this.Ig[e]||(this.Ig[e]=aa(),this.Ig[e].request=
{t:"text",p:e},this.ef(this.Ig[e].request));return this.Ig[e].promise},k1:function(e,f,h,n){var r=this.mf.length;this.Cw.length&&(r=this.Cw.pop());this.mf[r]=aa();this.mf[r].request={t:"tiles",p:e,z:f,r:h,size:n,rID:r};this.ef(this.mf[r].request);return this.mf[r].promise},wN:function(){this.Qe||(this.Qe=aa(),this.Qe.request={t:"pdf"},this.eB?this.Qe.resolve({url:this.lB}):this.ef(this.Qe.request));return this.Qe.promise},FK:function(e){var f=this,h=new XMLHttpRequest,n=this.Hf+"aul?id="+this.id+
"&bcid="+this.Tf.clientId,w=new FormData,x={};e.annots&&(x.annots="xfdf");e.watermark&&(x.watermark="png");e.redactions&&(x.redactions="redact");x={t:"docmod",reqID:this.U_++,parts:x};e.print&&(x.print=!0);var y=this.VI(x);w.append("msg",JSON.stringify(y));return Promise.all([e.annots,e.watermark,e.redactions].map(function(e){return Promise.resolve(e)})).then(function(e){var r=e[0],x=e[1],z=e[2];r&&w.append("annots",r);x&&w.append("watermark",e.watermark);z&&w.append("redactions",z);f.Hx[y.reqID]=
aa();h.open("POST",n);h.withCredentials=f.Xm;h.send(w);return f.Hx[y.reqID].promise})},kL:function(){this.Sd||(this.Sd=aa(),this.Sd.request={t:"xod",noCreate:!0},this.ef(this.Sd.request));return this.Sd.promise},l1:function(){this.he||(this.he=aa(),this.he.request={t:"xod"},this.ef(this.he.request));return this.he.promise},Gl:function(){return!0},request:function(){},fN:function(){},abort:function(){for(var e=0;e<this.mf.length;e++)this.mf[e]&&(this.mf[e].resolve(null),this.mf[e]=null,this.Cw.push(e));
this.close()},zy:function(e){this.df=this.df||{};this.df.headers=e},F6:function(){return this.df?Object(z.omit)(this.df.headers,["Cookie","cookie"]):null},cq:function(e){this.df=this.df||{};this.df.internal=this.df.internal||{};this.df.internal.withCredentials=e},Xm:function(){return this.df&&this.df.internal?this.df.internal.withCredentials:null},getFileData:function(){return Promise.reject()}});Object(ia.b)(ca);Object(h.a)(ca);Object(h.b)(ca);da["default"]=ca},370:function(ia,da,h){function ca(h){for(var z=
"",x=0;x<h;x++)z+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(62*Math.random()));return z}function aa(h,z,x){function n(f,e,h){function n(e){w().then(function(f){da&&!ea?setTimeout(function(){n(e)},1):f.send(JSON.stringify(e))})}function r(e,f,r){var w=window.createPromiseCapability(),ba=!1,ha=w;z=e;aa=f;ca=r;y=null;try{e=fa?ia+"/"+fa:ia+"/ws";e+="?bcid="+h;var ja=new WebSocket(e);ja.onopen=function(){w.resolve();ba=!0;w=null;da=!1;x.resolve(ja);aa&&aa()};ja.onerror=
function(e){da=ea=!0;w&&w.reject(e);y&&y.reject()};ja.onclose=function(){x=window.createPromiseCapability();da=!0;y||(y=window.createPromiseCapability());y.resolve();ca&&ca();z&&ba&&z({t:"health",data:{unhealthy:!0,isDead:!0}})};ja.onmessage=function(e){e&&e.data&&(e=JSON.parse(e.data),e.hb?n({hb:!0}):e.end?close():z(e))}}catch(Ba){w.reject(Ba),w=null}return ha.promise}function w(){da&&z&&r(z);return x.promise}var x=window.createPromiseCapability(),y=null,z,aa,ca=null,da=!1,ea=!1,fa=e,ia=function(e){var f=
e.indexOf("://"),h="ws://";0>f?f=0:(5===f&&(h="wss://"),f+=3);var n=e.lastIndexOf("/");0>n&&(n=e.length);return h+e.slice(f,n)}(f);return{send:n,OE:r,vB:function(){return y?y.promise:w().then(function(e){y=window.createPromiseCapability();z=null;e.close();return y.promise})},clientId:h}}function f(f){var e=f.lastIndexOf("/");0>e&&(e=f.length);return f.slice(0,e)}var y=ca(8);return window.WebSocket&&!x?n(h,z,y):function(h,e,n){function r(e){(da?da.promise:Promise.resolve(ca)).then(function(f){var h=
new XMLHttpRequest;f=aa?z+"/"+aa+"pf?id="+f:z+"/pf?id="+f;f+="&bcid="+n;var r=new FormData;r.append("data",JSON.stringify(e));h.open("POST",f);h.withCredentials=!0;h.send(r)})}function w(){ca=0;da||(da=window.createPromiseCapability())}function x(){y=new XMLHttpRequest;var e=z+"/pf";e=0!==ca?e+("?id="+ca+"&uc="+va):e+("?uc="+va);va++;y.open("GET",e,!0);y.withCredentials=!0;y.setRequestHeader("Cache-Control","no-cache");y.setRequestHeader("X-Requested-With","XMLHttpRequest");var f=y,h=!1;y.onreadystatechange=
function(){a:if(3<=f.readyState&&!h){try{var e=f.responseText.length}catch(za){Object(fa.f)("caught exception");break a}if(0<e)try{var n=f.responseText.split("\n");for(n[n.length-1]&&n.pop();0<n.length&&3>n[n.length-1].length;)"]"===n.pop()&&w();0<n.length&&3>n[0].length&&n.shift();for(e=0;e<n.length;++e)n[e].endsWith(",")&&(n[e]=n[e].substr(0,n[e].length-1));0===ca&&0<n.length&&(ca=JSON.parse(n.shift()).id,e=da,da=null,e.resolve(ca));var y;for(e=0;e<n.length;++e)(y=JSON.parse(n[e]))&&y.end?close():
y&&y.hb&&y.id===ca?r({hb:!0}):Aa(y)}catch(za){}ea||(h=!0,x())}};y.send()}var y,z=f(h),aa=e,ca=0,da=window.createPromiseCapability(),ea=!1,ia=null,Aa=null,va=0;return{send:r,OE:function(e,f,h){Aa=e;ia=h;ea=!1;w();x();f&&f();return Promise.resolve()},vB:function(){w();Aa=null;ea=!0;ia&&ia();y.abort();return Promise.resolve()},clientId:n}}(h,z,y)}h.d(da,"a",function(){return aa});var fa=h(1)}}]);}).call(this || window)
