/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see legal.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[11],{360:function(ia,da,h){h.r(da);var ca=h(369),aa=h(90),fa=h(30),ea=h(54);ia=function(){function h(){this.nb=this.ce=this.Cb=this.Qb=null;this.re=!1}h.prototype.clear=function(){Object(fa.b)(this.Qb);this.Cb="";Object(fa.b)(this.ce);Object(fa.b)(this.nb);this.re=!1};h.prototype.tc=function(){this.Qb=[];this.ce=[];this.nb=[];this.re=!1};h.prototype.Yu=function(h){for(var n="",f=0,x,w,e;f<h.length;)x=h.charCodeAt(f),9==x?(n+=String.fromCharCode(10),
f++):128>x?(n+=String.fromCharCode(x),f++):191<x&&224>x?(w=h.charCodeAt(f+1),n+=String.fromCharCode((x&31)<<6|w&63),f+=2):(w=h.charCodeAt(f+1),e=h.charCodeAt(f+2),n+=String.fromCharCode((x&15)<<12|(w&63)<<6|e&63),f+=3);return n};h.prototype.initData=function(h){this.Qb=[];this.ce=[];this.nb=[];this.re=!1;try{var n=new ea.a(h);this.Cb="";n.Ca();if(!n.advance())return;var f=n.current.textContent;this.Cb=f=this.Yu(f);Object(fa.b)(this.ce);n.advance();f=n.current.textContent;for(var x=f.split(","),w=
Object(aa.a)(x);w.Zj();){var e=w.current;try{var r=parseInt(e.trim());this.ce.push(r)}catch(pa){}}Object(fa.b)(this.Qb);n.advance();f=n.current.textContent;x=f.split(",");for(var z=Object(aa.a)(x);z.Zj();){e=z.current;try{r=parseFloat(e.trim()),this.Qb.push(r)}catch(pa){}}Object(fa.b)(this.nb);n.advance();f=n.current.textContent;x=f.split(",");h=[];n=[];f=0;for(var ca=Object(aa.a)(x);ca.Zj();){e=ca.current;switch(e){case "Q":f=1;break;case "R":f=2;break;case "S":f=3;break;default:f=0}if(f)h.push(0),
n.push(f);else try{r=parseFloat(e.trim()),h.push(r),n.push(f)}catch(pa){return}}f=0;var da=h.length;for(ca=e=x=0;ca<da;){var ia=n[ca];if(0<ia)f=ia,++ca,3===f&&(x=h[ca],e=h[ca+1],ca+=2);else if(1===f)for(r=0;8>r;++r)this.nb.push(h[ca++]);else if(2===f){var ta=h[ca++];var ka=h[ca++];var ma=h[ca++];var wa=h[ca++];this.nb.push(ta);this.nb.push(ka);this.nb.push(ma);this.nb.push(ka);this.nb.push(ma);this.nb.push(wa);this.nb.push(ta);this.nb.push(wa)}else 3===f&&(ta=h[ca++],ka=x,ma=h[ca++],wa=e,this.nb.push(ta),
this.nb.push(ka),this.nb.push(ma),this.nb.push(ka),this.nb.push(ma),this.nb.push(wa),this.nb.push(ta),this.nb.push(wa))}}catch(pa){return}this.Cb.length&&this.Cb.length===this.ce.length&&8*this.Cb.length===this.nb.length&&(this.re=!0)};h.prototype.ready=function(){return this.re};h.prototype.ks=function(){var h=new ca.a;if(!this.Qb.length)return h.$f(this.Qb,-1,this.Cb,this.nb,0),h;h.$f(this.Qb,1,this.Cb,this.nb,1);return h};h.prototype.Le=function(){return this.nb};h.prototype.getData=function(){return{m_Struct:this.Qb,
m_Str:this.Cb,m_Offsets:this.ce,m_Quads:this.nb,m_Ready:this.re}};return h}();da["default"]=ia},369:function(ia,da,h){var ca=h(51),aa=h(199),fa=h(382);ia=function(){function h(){this.Dd=0;this.eb=this.wa=this.Ae=null;this.mc=0;this.Cd=null}h.prototype.tc=function(){this.Dd=-1;this.mc=0;this.Cd=[]};h.prototype.$f=function(h,x,n,f,y){this.Dd=x;this.mc=y;this.Cd=[];this.Ae=h;this.wa=n;this.eb=f};h.prototype.Ia=function(h){return this.Dd===h.Dd};h.prototype.pi=function(){return Math.abs(this.Ae[this.Dd])};
h.prototype.Xj=function(){return 0<this.Ae[this.Dd]};h.prototype.Bc=function(){var h=this.Xj()?6:10,x=new fa.a;x.$f(this.Ae,this.Dd+h,this.Dd,this.wa,this.eb,1);return x};h.prototype.jL=function(h){if(0>h||h>=this.pi()){var x=new fa.a;x.$f(this.Ae,-1,-1,this.wa,this.eb,0);return x}var n=this.Xj()?6:10,f=this.Xj()?5:11;x=new fa.a;x.$f(this.Ae,this.Dd+n+f*h,this.Dd,this.wa,this.eb,1+h);return x};h.prototype.Bf=function(){var z=this.Dd+parseInt(this.Ae[this.Dd+1]);if(z>=this.Ae.length){var x=new h;x.$f(this.Ae,
-1,this.wa,this.eb,0);return x}x=new h;x.$f(this.Ae,z,this.wa,this.eb,this.mc+1);return x};h.prototype.bc=function(h){if(this.Xj())h.fa=this.Ae[this.Dd+2+0],h.da=this.Ae[this.Dd+2+1],h.ga=this.Ae[this.Dd+2+2],h.ea=this.Ae[this.Dd+2+3];else{for(var x=1.79769E308,n=ca.a.MIN,f=1.79769E308,y=ca.a.MIN,w=0;4>w;++w){var e=this.Ae[this.Dd+2+2*w],r=this.Ae[this.Dd+2+2*w+1];x=Math.min(x,e);n=Math.max(n,e);f=Math.min(f,r);y=Math.max(y,r)}h.fa=x;h.da=f;h.ga=n;h.ea=y}};h.prototype.li=function(){if(this.Cd.length)return this.Cd[0];
var h=new aa.a,x=new aa.a,n=new fa.a;n.tc();var f=this.Bc(),y=new fa.a;y.tc();for(var w=this.Bc();!w.Ia(n);w=w.bf())y=w;n=Array(8);w=Array(8);f.oe(0,n);h.x=(n[0]+n[2]+n[4]+n[6])/4;h.y=(n[1]+n[3]+n[5]+n[7])/4;y.oe(y.Wc()-1,w);x.x=(w[0]+w[2]+w[4]+w[6])/4;x.y=(w[1]+w[3]+w[5]+w[7])/4;.01>Math.abs(h.x-x.x)&&.01>Math.abs(h.y-x.y)&&this.Cd.push(0);h=Math.atan2(x.y-h.y,x.x-h.x);h*=180/3.1415926;0>h&&(h+=360);this.Cd.push(h);return 0};return h}();da.a=ia},382:function(ia,da,h){var ca=h(369),aa=h(109),fa=h(51);
ia=function(){function h(){this.hj=this.hd=0;this.eb=this.wa=this.Qb=null;this.mc=0}h.prototype.tc=function(){this.hj=this.hd=-1;this.mc=0};h.prototype.$f=function(h,x,n,f,y,w){this.hd=x;this.hj=n;this.Qb=h;this.wa=f;this.eb=y;this.mc=w};h.prototype.Ia=function(h){return this.hd===h.hd};h.prototype.Wc=function(){return parseInt(this.Qb[this.hd])};h.prototype.oh=function(){return parseInt(this.Qb[this.hd+2])};h.prototype.Hb=function(){return parseInt(this.Qb[this.hd+1])};h.prototype.Xj=function(){return 0<
this.Qb[this.hj]};h.prototype.gY=function(){return Math.abs(this.Qb[this.hj])};h.prototype.bf=function(){var z=this.Xj(),x=z?5:11;if(this.hd>=this.hj+(z?6:10)+(this.gY()-1)*x)return z=new h,z.$f(this.Qb,-1,-1,this.wa,this.eb,0),z;z=new h;z.$f(this.Qb,this.hd+x,this.hj,this.wa,this.eb,this.mc+1);return z};h.prototype.HX=function(h){var x=this.Wc();return 0>h||h>=x?-1:parseInt(this.Qb[this.hd+1])+h};h.prototype.oe=function(h,x){h=this.HX(h);if(!(0>h)){var n=new ca.a;n.$f(this.Qb,this.hj,this.wa,this.eb,
0);if(n.Xj()){var f=new aa.a;n.bc(f);n=f.da<f.ea?f.da:f.ea;f=f.da>f.ea?f.da:f.ea;h*=8;x[0]=this.eb[h];x[1]=n;x[2]=this.eb[h+2];x[3]=x[1];x[4]=this.eb[h+4];x[5]=f;x[6]=this.eb[h+6];x[7]=x[5]}else for(h*=8,n=0;8>n;++n)x[n]=this.eb[h+n]}};h.prototype.Kd=function(h){var x=new ca.a;x.$f(this.Qb,this.hj,this.wa,this.eb,0);if(x.Xj()){var n=this.Qb[this.hd+3],f=this.Qb[this.hd+4];if(n>f){var y=n;n=f;f=y}y=new aa.a;x.bc(y);x=y.da<y.ea?y.da:y.ea;y=y.da>y.ea?y.da:y.ea;h[0]=n;h[1]=x;h[2]=f;h[3]=x;h[4]=f;h[5]=
y;h[6]=n;h[7]=y}else for(n=this.hd+3,f=0;8>f;++f)h[f]=this.Qb[n+f]};h.prototype.bc=function(h){var x=new ca.a;x.$f(this.Qb,this.hj,this.wa,this.eb,0);if(x.Xj()){var n=this.Qb[this.hd+3],f=this.Qb[this.hd+4];if(n>f){var y=n;n=f;f=y}y=new aa.a;x.bc(y);x=y.da<y.ea?y.da:y.ea;y=y.da>y.ea?y.da:y.ea;h[0]=n;h[1]=x;h[2]=f;h[3]=y}else{n=1.79769E308;f=fa.a.MIN;x=1.79769E308;y=fa.a.MIN;for(var w=this.hd+3,e=0;4>e;++e){var r=this.Qb[w+2*e],z=this.Qb[w+2*e+1];n=Math.min(n,r);f=Math.max(f,r);x=Math.min(x,z);y=Math.max(y,
z)}h[0]=n;h[1]=x;h[2]=f;h[3]=y}};return h}();da.a=ia}}]);}).call(this || window)
